name: mse463-563
channels:
  - conda-forge
  - bioconda
dependencies:
  - ele
  - foyer=0.7.7
  - gsd=2.4.0
  - hoomd=2.9.4
  - mdtraj
  - numpy=1.20.1
  - packmol>=18
  - parmed>=3.4.0
  - pip=21.0
  - pytest
  - mdanalysis
  - pytest-cov
  - python=3.7
  - rdkit=2021.03.1
  - scipy=1.6.0
  - matplotlib
  - nglview
  - notebook
  - nb_conda_kernels
  - pip:
      - git+https://github.com/mosdef-hub/mbuild
      - git+https://github.com/cmelab/uli-init.git@0.2.0